spring:
  application:
    name: robot-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name:
#    username: root
#    password: root
#    url: jdbc:mysql://localhost:3306/robot?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT
    url: jdbc:mysql://mysql.jwjjgs.cn:6033/robot?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&allowMultiQueries=true&tinyInt1isBit=false
    username: root
    password: qwer1234.

mybatis-plus:
    mapper-locations: classpath:mapper/*/*.xml
    type-aliases-package: com.first.litapp_dn.pojo
    configuration:
      map-underscore-to-camel-case: true
    global-config:
      db-config:
        logic-not-delete-value: N
        logic-delete-value: Y
        logic-delete-field: deleteFlag
grpc:
  server:
    port: 8082

server:
  port: 8080

netty:
  port: 8081

jwt:
  secret: qweasd/><zxc123[]\qweasd/><zxc123[]